setLocal(os.getenv('DNSDIST_BIND_ADDRESS') or '10.89.61.2:53')
setACL({os.getenv('DNSDIST_ALLOW_FROM') or '10.89.60.0/24, 10.89.61.0/24'})

-- to limit memory overhead
setMaxUDPOutstanding(4096)

-- dnsdist upstream resolvers (newServer entries)
-- list on https://www.ipfire.org/docs/dns/public-servers
newServer({address="1.1.1.1:53"}) -- Cloudflare
newServer({address="1.0.0.1:53"}) -- Cloudflare
newServer({address="[2606:4700:4700::1111]:53"}) -- Cloudflare IPv6
newServer({address="[2606:4700:4700::1001]:53"}) -- Cloudflare IPv6
newServer({address="76.76.2.0:53"}) -- Control D Free Uncensored
newServer({address="76.76.10.0:53"}) -- Control D Free Uncensored
newServer({address="[2606:1a40::]:53"}) -- Control D Free Uncensored
newServer({address="[2606:1a40:1::]:53"}) -- Control D Free Uncensored
newServer({address="185.222.222.222:53"}) -- dns.sb
newServer({address="45.11.45.11:53"}) -- dns.sb
newServer({address="[2a09::]:53"}) -- dns.sb
newServer({address="[2a11::]:53"}) -- dns.sb
newServer({address="8.8.8.8:53"}) -- Google Public Free DNS
newServer({address="8.8.4.4:53"}) -- Google Public Free DNS
newServer({address="194.242.2.2:53"}) -- Mullvad
newServer({address="[2a07:e340::2]:53"}) -- Mullvad IPv6
newServer({address="5.1.66.255:53"}) -- Freifunk Muenchen e.V.
newServer({address="[2001:678:e68:f000::]:53"}) -- Freifunk Muenchen e.V.
newServer({address="185.150.99.255:53"}) -- Freifunk Muenchen e.V.
newServer({address="[2001:678:ed0:f000::]:53"}) -- Freifunk Muenchen e.V.
newServer({address="81.3.27.54:53"}) -- Lightning Wire Labs
newServer({address="[2001:678:b28::54]:53"}) -- Lightning Wire Labs
newServer({address="95.217.11.63:53"}) -- NWPS.fi
newServer({address="[2a01:4f9:c012:25a0::1]:53"}) -- NWPS.fi
newServer({address="135.181.103.31:53"}) -- NWPS.fi
newServer({address="[2a01:4f9:c011:aa31::1]:53"}) -- NWPS.fi
newServer({address="80.67.169.12:53"}) -- French Data Network (FDN)
newServer({address="[2001:910:800::12]:53"}) -- French Data Network (FDN)
newServer({address="80.67.169.40:53"}) -- French Data Network (FDN)
newServer({address="[2001:910:800::40]:53"}) -- French Data Network (FDN)
newServer({address="45.80.1.6:53"}) -- LinuxPatch.com
newServer({address="[2a0e:3780:1::3:38]:53"}) -- LinuxPatch.com
newServer({address="75.75.75.75:53"}) -- Comcast / Xfinity
newServer({address="75.75.76.76:53"}) -- Comcast / Xfinity
newServer({address="64.6.64.6:53"}) -- Verisign
newServer({address="64.6.65.6:53"}) -- Verisign

newServer({address="86.54.11.100"}) -- DNS4EU
newServer({address="[2a13:1001::86:54:11:100]"}) -- DNS4EU