services:
  proxy-http:
    build:
      context: .github/docker/tinyproxy
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8888:8888"

  proxy-socks:
    image: serjs/go-socks5-proxy:latest
    environment:
      - REQUIRE_AUTH=false
    ports:
      - "127.0.0.1:1080:1080"
