from typing import Any, Protocol, runtime_checkable

from selenium.webdriver.chrome.webdriver import WebDriver


@runtime_checkable
class Element(Protocol):
    """Protocol for DOM elements."""

    def click(self) -> None: ...
    def clear(self) -> None: ...
    def send_keys(self, text: str) -> None: ...
    def get_attribute(self, name: str) -> str | None: ...

    @property
    def text(self) -> str: ...

    @property
    def location(self) -> dict[str, int]: ...

    @property
    def size(self) -> dict[str, int]: ...


@runtime_checkable
class ActionChainBuilder(Protocol):
    """Protocol for action chains (like Selenium ActionChains)."""

    def move_to_element(self, element: Element) -> "ActionChainBuilder": ...
    def move_by_offset(self, x: int, y: int) -> "ActionChainBuilder": ...
    def pause(self, seconds: float) -> "ActionChainBuilder": ...
    def click(self, element: Element | None = None) -> "ActionChainBuilder": ...
    def click_and_hold(self) -> "ActionChainBuilder": ...
    def release(self) -> "ActionChainBuilder": ...
    def send_keys(self, *keys: str) -> "ActionChainBuilder": ...
    def perform(self) -> None: ...


@runtime_checkable
class BrowserContext(Protocol):
    """Protocol abstracting browser operations for Selenium and Playwright."""

    # Navigation
    def get(self, url: str) -> None: ...

    # Scripting
    def execute_script(self, script: str, *args: Any) -> Any: ...

    # Querying
    def find_element(self, by: str, value: str) -> Element: ...
    def find_elements(self, by: str, value: str) -> list[Element]: ...

    # Page state
    @property
    def page_source(self) -> str: ...

    @property
    def title(self) -> str: ...

    @property
    def current_url(self) -> str: ...

    # Cookies
    def add_cookie(self, cookie: dict[str, Any]) -> None: ...
    def delete_cookie(self, name: str) -> None: ...
    def get_cookies(self) -> list[dict[str, Any]]: ...

    # Screenshot
    def get_screenshot_as_base64(self) -> str: ...

    # Switch to
    def switch_to_default_content(self) -> None: ...
    def get_alert_text(self) -> str: ...
    def dismiss_alert(self) -> None: ...

    # Lifecycle
    def close(self) -> None: ...
    def quit(self) -> None: ...

    # CDP
    def execute_cdp_cmd(self, method: str, params: dict[str, Any]) -> Any: ...

    # Actions
    def action_chain(self) -> ActionChainBuilder: ...

    # Waits
    def wait_for_presence(self, by: str, value: str, timeout: float) -> Element: ...
    def wait_for_absence(self, by: str, value: str, timeout: float) -> bool: ...
    def wait_for_visibility(self, by: str, value: str, timeout: float) -> Element: ...
    def wait_for_title(self, title: str, timeout: float) -> bool: ...
    def wait_for_title_not(self, title: str, timeout: float) -> bool: ...
    def wait_for_staleness(self, element: Element, timeout: float) -> bool: ...

    # User agent helpers
    def get_user_agent(self) -> str: ...
    def apply_user_agent_override(self, user_agent: str) -> None: ...


def get_browser_context(driver: WebDriver | BrowserContext) -> BrowserContext:
    """Normalize a raw WebDriver or an existing BrowserContext into a BrowserContext."""
    # Avoid treating mock objects as BrowserContext (runtime_checkable Protocol
    # matches MagicMock because it returns True for any hasattr check).
    from flaresolverr.backends.selenium_context import SeleniumBrowserContext

    if isinstance(driver, SeleniumBrowserContext):
        return driver
    try:
        from flaresolverr.backends.camoufox import CamoufoxBrowserContext

        if isinstance(driver, CamoufoxBrowserContext):
            return driver
    except ImportError:
        pass
    return SeleniumBrowserContext(driver)
